spring.application.name=pokemon-tcg-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pokemon_tcg
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html